### PR TITLE
fixed duplicate answers : fixed issue #612

### PR DESCRIPTION
**Pull request by akashbilgi**
1) fixed multiple calls to sanitize ( **resanitize issue for "saved" question** )
- this also prevent  going thru al the item in answers.json and printing it on lterminal/logger 
- the answers are already saved by sanitizing - it doesnt need resanitizeing when looping through

Example

```
>  for item in self.all_data:
>                 if **self._sanitize_text(question_text)** in item['question'] and item['type'] == 'radio':
>                     existing_answer = item
```
this called sanitize every question that was ever saved and prited the question on output/logger

2) (**resanitize issue of LinkedIn question**) is fixed

3) **reloaded answers** from json once they are saved so we can get new asnwers when needed

4) Moreover all the answers were saved **(duplicated)** in many scenarios when the question/answer are presetn - the if statement was fixed to allowed only non duplicates

fixes issue #612

### CODE REVIEW

**Comment by akashbilgi** [comment]
@feder-cr  review please

**Comment by surapuramakhil** [comment]
I guess 1 reviewer is enough. unassigning myself for this

**Comment by akashbilgi** [comment]
closing this - since too many change and stale PR.. 

- wont fix this 

thanks

**Comment by feder-cr** [comment]
@akashbilgi can you work on this?

**Comment by akashbilgi** [comment]
@feder-cr ok - assign it to me , i have to clean up my repo and will push changes today evening

**Comment by akashbilgi** [comment]
@feder-cr clos this PR - i have raise a new PR:
https://github.com/AIHawk-co/Auto_Jobs_Applier/pull/777

**Pull request closed without merging**
