### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ShotgunShinobi**
Corrected the descriptions of hybrid and onsite jobs under config.yaml file

### CODE REVIEW

**Review by cjbbb — APPROVED** [review]

**Comment by surapuramakhil** [comment]
Merging this PR as @cjbbb approved

**Comment by cjbbb** [comment]
one minute. He changed more than last time I reviewed @surapuramakhil

**Comment by cjbbb** [comment]
@ShotgunShinobi Thanks for your help. Could you pls resolve the conflicts?

**Comment by surapuramakhil** [comment]
@ShotgunShinobi can you synchronize you branch - just merge release branch into your branch.

**Comment by ShotgunShinobi** [comment]
> @ShotgunShinobi can you synchronize you branch - just merge release branch into your branch.

I got a bit busy with uni, sorry I couldn't respond in time.

**Comment by surapuramakhil** [comment]
it's okay, we merged your PR.

**Pull request merged**
